import importlib.metadata as _metadata

from . import performance, plotting, tears, utils
from .utils import (
    CleanFactorResult,
    LossReport,
    MaxLossExceededError,
    NonMatchingTimezoneError,
    add_custom_calendar_timedelta,
    backshift_returns_series,
    compute_forward_returns,
    demean_forward_returns,
    diff_custom_calendar_timedeltas,
    get_clean_factor,
    get_clean_factor_and_forward_returns,
    get_forward_returns_columns,
    infer_trading_calendar,
    non_unique_bin_edges_error,
    print_table,
    quantize_factor,
    rate_of_return,
    rethrow,
    std_conversion,
    timedelta_strings_to_integers,
    timedelta_to_string,
    validate_factor_frame,
)

__version__ = _metadata.version("ferric-alpha")

__all__ = [
    "__version__",
    "add_custom_calendar_timedelta",
    "backshift_returns_series",
    "CleanFactorResult",
    "demean_forward_returns",
    "diff_custom_calendar_timedeltas",
    "LossReport",
    "MaxLossExceededError",
    "NonMatchingTimezoneError",
    "compute_forward_returns",
    "get_forward_returns_columns",
    "get_clean_factor",
    "get_clean_factor_and_forward_returns",
    "infer_trading_calendar",
    "non_unique_bin_edges_error",
    "print_table",
    "quantize_factor",
    "performance",
    "plotting",
    "rate_of_return",
    "rethrow",
    "std_conversion",
    "tears",
    "timedelta_strings_to_integers",
    "timedelta_to_string",
    "utils",
    "validate_factor_frame",
]
